[package]
name = "yamerkle"
version = "0.1.0"
authors = ["zruchala"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.9.1"
hex = "0.4.3"
structopt = "0.3"
